/* 
  Sketch generated by the Arduino IoT Cloud Thing "iot-cloud-analog-thing"
  https://create.arduino.cc/cloud/things/713aba1c-9b09-4adc-8243-f2863f611d98 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool fan;
  bool tubelight;
  bool night_bulb;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define LED 2 //Connect relay1(Connected to LED) to pin 2
#define NIGHT_BULB 3 //Connect relay2(Connected to NIGHT_BULB) to pin 3
#define FAN 4 //Connect relay3(Connected to FAN) to pin 4
#define TUBELIGHT 5 //Connect relay4(Connected to TUBELIGHT) to pin 5

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(LED, OUTPUT); //Set relay1 as an output
  pinMode(NIGHT_BULB, OUTPUT); //Set relay2 as an output
  pinMode(FAN, OUTPUT); //Set relay1 as an output
  pinMode(TUBELIGHT, OUTPUT); //Set relay2 as an output
 
  digitalWrite(LED, LOW); //Switch LED off
  digitalWrite(NIGHT_BULB, LOW); //Swtich NIGHT_BULB off
  digitalWrite(FAN, LOW); //Switch FAN off
  digitalWrite(TUBELIGHT, LOW); //Swtich TUBELIGHT off
}

void loop() {
  ArduinoCloud.update();
}

void onLedChange() {
  digitalWrite(LED, led);
}

void onTubelightChange() {
  digitalWrite(TUBELIGHT, tubelight);
}

void onFanChange() {
  digitalWrite(FAN, fan);
}

void onNightBulbChange() {
  digitalWrite(NIGHT_BULB, night_bulb);
}
